
export const prismaSampleData = {
  products: [
    {
      name: "Camisa Polo Sporting Stretch",
      slug: "camisa-polo-sporting-stretch",
      category: "Camisas sociais masculinas",
      description: "Estilo polo clássico com conforto moderno",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 59.99,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Camisa manga longa Brooks Brothers",
      slug: "camisa-manga-longa-brooks-brothers",
      category: "Camisas sociais masculinas",
      description: "Estilo atemporal e conforto premium",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      price: 85.9,
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Camisa social Tommy Hilfiger Classic Fit",
      slug: "camisa-social-tommy-hilfiger-classic-fit",
      category: "Camisas sociais masculinas",
      description: "Uma mistura perfeita de sofisticação e conforto",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      price: 99.95,
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Camisa Calvin Klein Slim Fit Stretch",
      slug: "camisa-calvin-klein-slim-fit-stretch",
      category: "Camisas sociais masculinas",
      description: "Design aerodinâmico com tecido elástico flexível",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      price: 39.95,
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Camisa Polo Ralph Lauren Oxford",
      slug: "camisa-polo-ralph-lauren-oxford",
      category: "Camisas sociais masculinas",
      description: "Design icônico do Polo com tecido oxford refinado",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      price: 79.99,
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Classic Rosa com capuz",
      slug: "polo-classic-rosa-com-capuz",
      category: "Moletons Masculinos",
      description: "Macio, elegante e perfeito para dias descontraídos",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 99.99,
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};
